from django.urls import path
from .views import (
    ActivityListView,
    ActivityCreateView,
    JoinActivityView,
    MyParticipationsView,
    AttendanceListCreateView,
    MyTotalHoursView,
    DailyActivityLogListCreateView,
    DailyActivityStatisticsView,
    DailyActivityReportView,
    VolunteerHoursReportView,
    DashboardStatisticsView,
    OrganizationsReportView,
    ActivityDetailView,
    MyOrganizationActivitiesView,
    MyOrganizationApplicationsView,
    ActivityApplicationsView,
    ActivityUpdateView,
    ApproveParticipationView,
    RejectParticipationView,
    ActivitySettingsView,
    CancelParticipationView,
)

urlpatterns = [
    path('', ActivityListView.as_view(), name='activity-list'),
    path('create/', ActivityCreateView.as_view(), name='activity-create'),
    path(
        "my-activities/",
        MyOrganizationActivitiesView.as_view(),
        name="my-activities",
),
    path(
        "my-applications/",
        MyOrganizationApplicationsView.as_view(),
        name="my-applications",
),
    path(
        "<int:pk>/applications/",
        ActivityApplicationsView.as_view(),
        name="activity-applications",
),
    path(
        "<int:pk>/update/",
        ActivityUpdateView.as_view(),
        name="activity-update",
),
    path(
        "participations/<int:pk>/approve/",
        ApproveParticipationView.as_view(),
        name="approve-participation",
),

    path(
        "participations/<int:pk>/reject/",
        RejectParticipationView.as_view(),
        name="reject-participation",
),
    path(
        "<int:pk>/",
        ActivityDetailView.as_view(),
        name="activity-detail"
),
    path(
        '<int:pk>/join/',
        JoinActivityView.as_view(),
        name='activity-join'
    ),

    path(
        'my-participations/',
        MyParticipationsView.as_view(),
        name='my-participations'
    ),

    path(
        'attendance/',
        AttendanceListCreateView.as_view(),
        name='attendance-list-create'
    ),

    path(
        "my-total-hours/",
        MyTotalHoursView.as_view(),
        name="my-total-hours",
),
    path(
        'daily-logs/',
        DailyActivityLogListCreateView.as_view(),
        name='daily-logs'
),
    path(
       'daily-logs/statistics/',
       DailyActivityStatisticsView.as_view(),
       name='daily-log-statistics'
),
    path(
       "daily-logs/report/",
       DailyActivityReportView.as_view(),
       name="daily-log-report",
),
    path(
       "volunteer-hours-report/",
       VolunteerHoursReportView.as_view(),
       name="volunteer-hours-report",
),
    path(
       "dashboard/",
       DashboardStatisticsView.as_view(),
       name="dashboard",
),
    path(
       "organizations-report/",
       OrganizationsReportView.as_view(),
       name="organizations-report",
),
    path(
       "settings/",
       ActivitySettingsView.as_view(),
       name="activity-settings",
),
   path(
      "participations/<int:pk>/cancel/",
      CancelParticipationView.as_view(),
      name="cancel-participation"
),


]