# Generated by Django 5.2.14 on 2026-05-23 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('environment', 'Environment'), ('health', 'Health'), ('education', 'Education'), ('community', 'Community')], default='community', max_length=50)),
                ('location', models.CharField(default='Gaza', max_length=255)),
                ('start_date', models.DateField(default='2026-05-23')),
                ('end_date', models.DateField(default='2026-05-30')),
                ('volunteer_limit', models.PositiveIntegerField(default=20)),
                ('hours', models.PositiveIntegerField(default=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='organizations.organization')),
            ],
        ),
    ]
