# Generated by Django 5.1.3 on 2026-07-09 21:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0003_volunteerattendance"),
        ("organizations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="participation",
            unique_together={("user", "activity")},
        ),
        migrations.CreateModel(
            name="DailyActivityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("whatsapp", "استفسارات واتس أب"),
                            ("admission", "قضايا قبول وتسجيل"),
                            ("lecturers", "مراجعة محاضرين"),
                            ("administrative", "قضايا إدارية"),
                            ("elearning", "تعليم إلكتروني"),
                            ("volunteer", "مراجعات عمل تطوعي"),
                            ("technical", "دعم فني"),
                            ("calls", "اتصالات"),
                            ("sms", "رسائل SMS"),
                            ("institutions", "مخاطبات مؤسسات"),
                            ("field_visits", "زيارات ميدانية"),
                            ("design", "أعمال تصميم"),
                            ("media", "تصوير ومونتاج"),
                        ],
                        max_length=50,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("date", models.DateField()),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="daily_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="daily_logs",
                        to="organizations.organization",
                    ),
                ),
            ],
        ),
    ]
