# Generated by Django 5.1.3 on 2026-07-13 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0004_alter_participation_unique_together_dailyactivitylog"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="applicants_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="activity",
            name="registration_deadline",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="activity",
            name="status",
            field=models.CharField(
                choices=[("active", "Active"), ("closed", "Closed")],
                default="active",
                max_length=20,
            ),
        ),
    ]
