# Generated by Django 5.1.3 on 2026-08-03 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0005_activity_applicants_count_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="category",
            field=models.CharField(
                choices=[
                    ("technical", "Technical"),
                    ("medical", "Medical"),
                    ("educational", "Educational"),
                    ("administrative", "Administrative"),
                ],
                default="technical",
                max_length=50,
            ),
        ),
    ]
