# Generated by Django 5.1.3 on 2026-08-05 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0006_alter_activity_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="participation",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
