# Generated by Django 5.1.3 on 2026-08-08 15:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0007_alter_participation_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="hours",
            field=models.PositiveIntegerField(
                default=60,
                validators=[
                    django.core.validators.MinValueValidator(60),
                    django.core.validators.MaxValueValidator(120),
                ],
            ),
        ),
    ]
