# Generated by Django 5.1.3 on 2026-08-08 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0008_alter_activity_hours"),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivitySettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("minimum_hours", models.PositiveIntegerField(default=60)),
                ("maximum_hours", models.PositiveIntegerField(default=120)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name="activity",
            name="hours",
            field=models.PositiveIntegerField(default=60),
        ),
    ]
